### PR TITLE
fix the bug in remove

### PR DESCRIPTION
**Pull request by aghamir**
https://github.com/mjschultz/py-radix/issues/17

### CODE REVIEW

**Comment by mjschultz** [comment]
Good catch, and thanks! Can you add the short test case from your issue to the [test_regression.py](https://github.com/mjschultz/py-radix/blob/master/tests/test_regression.py) file too please?

**Comment by aghamir** [comment]
Thank you for fast response. I've done it.

**Comment by mjschultz** [comment]
Thanks again, the version with your fix should now be available as [`py-radix==0.9.2`](https://pypi.python.org/pypi/py-radix/0.9.2).

**Comment by mjschultz** [comment]
Out of curiosity, what version of python were you using?

**Comment by aghamir** [comment]
2.7.6

**Pull request merged**
